#version: '3.8'
#
#services:
#  db:
#    image: mysql:8.0
#    container_name: mysql-container
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: Whatif@465ss
#      MYSQL_DATABASE: library_management
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#
#  manager:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: manager
#    container_name: manager-container
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/library_management
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: Whatif@465ss
#
#volumes:
#  db_data:
